In [1]:
import os, shutil, itertools, yaml, kornia, torchvision, sys, copy, math
from functools import partial
import dill as pickle
from importlib import reload
osp = os.path
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms
import torch
nn = torch.nn
F = nn.functional
import monai.transforms as mtr

In [2]:
from inrnet import args as args_module
from inrnet import jobs as job_mgmt
from inrnet import optim, util, losses
from inrnet.analysis import analyze
from inrnet.data import dataloader, kitti
from inrnet.experiments import depth
from inrnet import inn
%matplotlib inline
plt.rcParams["figure.figsize"] = (4.0, 3.0)
plt.rcParams['figure.dpi'] = 200

rescale_clip = mtr.ScaleIntensityRangePercentiles(lower=1, upper=99, b_min=0, b_max=255, clip=True, dtype=np.uint8)
rescale_noclip = mtr.ScaleIntensityRangePercentiles(lower=0, upper=100, b_min=0, b_max=255, clip=False, dtype=np.uint8)
rescale_float = mtr.ScaleIntensity()

TMP_DIR=osp.expanduser("~/code/diffcoord/temp")

rsync -av --ignore-existing \
clintonw@peppercorn.csail.mit.edu:/data/vision/polina/users/clintonw/code/placenta/results/unetr_00 Downloads/

## interactive

In [4]:
args = job_mgmt.get_job_args("inrcoco")
data_loader = dataloader.get_inr_dataloader(args)

In [9]:
reload(kitti);
data_loader = kitti.get_kitti_inr_dataloader()
inr, depth = next(data_loader)

In [40]:
points = torch.rand(64,2) * 2 - 1
spacing = .25

bin_ixs = torch.round(points / spacing).int()
bin_ixs = bin_ixs[:,0]*int(1/spacing*3) + bin_ixs[:,1]
bins = torch.unique(bin_ixs)
matches = bin_ixs.unsqueeze(0) == bins.unsqueeze(1) # (bin, point)
points_per_bin = tuple(matches.sum(1))
surviving_indices = [np.random.choice(x) for x in torch.where(matches)[1].split(points_per_bin)]

return points[surviving_indices]

In [85]:
neighbors_per_point = matches.sum(0)

tensor([1, 3, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 3, 1, 4, 4, 2, 2, 2, 1, 1, 2, 2, 2,
        2, 2, 3, 2, 1, 1, 2, 4, 1, 2, 1, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 2, 2,
        1, 2, 2, 2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 1, 4, 1])

In [ ]:
points_per_bin =

In [61]:
torch.where(matches[1])[0]

tensor([ 1, 53, 54])

In [60]:
np.random.choice()

53

(tensor([ 1, 53, 54]),)

In [97]:
import torchvision.models as models
m = models.efficientnet_b0()

In [28]:
reload(inn.polynomials);

In [6]:
coco_len = 118287
kitti_len = 80896

In [ ]:
for ix in range(0,coco_len,1600):
    if not osp.exists(f"/data/vision/polina/scratch/clintonw/datasets/coco/siren_{ix+63}.pt"):
        print("sh fit_inr.sh", f"coco{ix//1600}", "fit_coco", ix)

In [ ]:
for ix in range(0,kitti_len,800):
    if not osp.exists(f"/data/vision/polina/scratch/clintonw/datasets/inrnet/kitti/siren_{ix+63}.pt"):
        print("sh fit_inr.sh", f"skit{ix//800}", "fit_kitti", ix)

In [ ]:
"/data/vision/polina/scratch/clintonw/datasets/coco/annotations/panoptic_train2017"

In [ ]:
osp.exists(f"/data/vision/polina/users/clintonw/code/diffcoord/temp/kitti/siren_{ix+63}.pt")

In [60]:
paths = sorted(util.glob2("/data/vision/polina/scratch/clintonw/datasets/inrnet/kitti/siren_*.pt"))

In [ ]:
## search python strings
import os
osp = os.path
root = osp.expanduser("~/code/placenta/placenta")
query_string = 'load_img'
for folder, subfolders, files in os.walk(root):
    for file in files:
        if file.endswith(".py"):
            path = osp.join(folder, file)
            with open(path, 'r') as f:
                if query_string in f.read():
                    print(path)